[project]
name = "idss"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "pygraphviz>=1.14",
]

[tool.uv.workspace]
members = ["venv"]
